### ISSUE TITLE
Speed up colorize function

### ISSUE THREAD

**Issue by SirTheViking** [SirTheViking/logger#11]
Maybe change name to `colorise` too

**Comment by manio** [comment]
Hi,
Did you maybe was thinking about the improvement in the paris which is mentioned in this comment?
https://github.com/Drakulix/simplelog.rs/pull/87#issuecomment-963228859
Is it hard to implement such API?

**Comment by 0x20F** [comment]
Heya!

Should definitely be doable, although considering that something like this was never intended with the original design of the API it's something quite big to add now. I can't say for sure what (in the existing codebase) would need rewriting and/or extending.

It doesn't sound like a bad idea though, performance could definitely need some improvements in certain cases.
With that said you're more than welcome to open up a PR if you've got any direct ideas on how to implement this. If you want.
